### ISSUE TITLE
功能請求：分集下載

### ISSUE THREAD

**Issue by tansunit** [chazeon/python-vistopia#2]
- 時間：2023年5月3日
- 請求：增加分集下載功能

無意當中發現這個有用的命令行客戶端，感謝作者。

試用之後發現，目前能夠達成的是：

1. 使用 subscriptions 子命令可以列出所有已經訂閱的節目，每個節目有一個對應的 ID.
2. 使用上一步獲得的 ID 和節目名稱，再用 show-content --id [ID] 可以列出具體某個節目（比如「放晴早安」）包含的所有音頻文件，以及對應的 ID.

當我嘗試用 save-show --id [ID] 下載的時候，發現程序會自動下載某個節目（比如「放晴早安」）的所有音頻文件，也就是幾十、上百個音頻文件。

當我下載超過 30 個文件的時候，程序便會停止運行，猜測是因爲看理想的服務器端限制機器下載。

因此在想，是否有可能讓 save-show --id 的 ID 是每一個音頻文件的 ID（或者可以自己設置 ID 區間）, 而不是某一檔節目的 ID. 這樣就可以自己選擇下載具體哪些音頻文件，而不是默認下載整檔節目的音頻。

感謝！

**Comment by chazeon** [comment]
在最新的 2c1dac2 版本中已添加分集下载功能，可以用过 `--episode-id` 筛选多个分集，保存音频和文稿。分集 ID 会根据元数据中的 `sort_number` 键筛选。
