### ISSUE TITLE
下载遇到的两处问题

### ISSUE THREAD

**Issue by alanoy** [chazeon/python-vistopia#3]
1. 没有 ID3 tag 会报错中断
2. title 中带有 '/' 时会报错中断

**Comment by chazeon** [comment]
对于「没有 ID3 tag 会报错中断」的问题试试在使用命令行的时候加上 `--no-tag`？

**Comment by alanoy** [comment]
> 对于「没有 ID3 tag 会报错中断」的问题试试在使用命令行的时候加上 `--no-tag`？

没注意到这个 option，应该可以，下次遇到我再试试。

**Comment by alanoy** [comment]
用了 `--no-tag` 还是不行

**Comment by chazeon** [comment]
Fixed in #4
